name: portfolio_roz
description: Rafael Ortiz Zabl√©h's Portfolio
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.9.2-0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  feather_icons: ^1.2.0
  intl: any
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  device_frame: ^1.4.0
  vector_math: ^2.2.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/images/tech_tools/
    - assets/icons/
  fonts:
    - family: Norwester
      fonts:
        - asset: assets/fonts/norwester.otf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700